config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  get 'home/application'
  get 'users/index' => "users#index"
  get 'users/new'
  post 'users/create' => "users#create"
  get 'users/edit'
  post 'users/update' => "users#update"

  get "login" => "users#login_form"
  post 'users/login' => 'users#login'
  post"users/logout" => "users#logout"
  get "home/top" => "home#top"
  get "home/list" => "home#list"
  get "home/not_login" => "home#not_login"
  post "home/create" => "home#create"
  post "home/:post_id/destroy" => "home#destroy"
  get 'community/top' =>"community#top"
  get 'community/conversation' =>"community#conversation"
  get 'users/new' => 'users#new'

  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "home/question" => "home#question"
  get "home/mail" => "home#mail"

  get 'home/index'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, {presence: true}
  validates :post_id, {presence: true}

end

app/models/like_category.rb
class LikeCategory < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/post.rb
class Post < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord


  validates :email, {uniqueness: true}
 end

app/models/whisper.rb
class Whisper < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_search
  before_action :set_current_user

  def set_search
    #@search = Article.search(params[:q])
    @search = Post.ransack(params[:q]) #ransackメソッド推奨
    @search_posts = @search.result
  end
  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to("/home/top")
    end
  end

  #ストロングパラメーター
  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :image, :introduce, :age, :sex, :address)
  end

   def set_current_user
     @current_user = User.find_by(id: session[:user_id])
  end


end

app/controllers/community_controller.rb
class CommunityController < ApplicationController
  def top
  end
  def conversation
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :set_current_user

  def application

  end
  def index
  @posts = Post.all
  end
  def top
    from  = Time.now.at_beginning_of_day
    to    = (from + 6.day).at_end_of_day
    @posts = Post.where(created_at: from...to)
  end
  def new
    @post = Post.new
    @whisper = Whisper.new
  end
  def create
    @post = Post.new(
      title: params[:title],
      content: params[:content],
      user_id: @current_user.id
    )

    if @post.save
      @whisper = Whisper.new(
        user_id: @current_user.id,
        post_id: @post.id
      )
      @whisper.save
      flash[:notice] = "投稿が完了しました"
      redirect_to("/home/top")
    else
      render("home/top")
    end
  end

  def question

  end

  def mail

  end
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def list
    @posts = Post.where(user_id: @current_user.id)
  end

  def destroy
    @post = Post.find_by(
      user_id: @current_user.id,
      id: params[:post_id]
    )
    @post.destroy
    flash[:notice] = "削除が完了しました"
    redirect_to("/home/list")
  end

  def not_login
    flash[:notice] = "ログインまたはアカウント登録をしてください"
    redirect_to("/home/top")
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # before_actionに「:authenticate_user」を追加してください
  before_action :authenticate_user

  # createアクションを追加してください
  def create
    @like = Like.new(
      user_id: @current_user.id,
      post_id: params[:post_id]
    )
    @like.save
    redirect_to("/home/top")
  end

  def destroy
    @like = Like.find_by(
      user_id: @current_user.id,
      post_id: params[:post_id]
    )
    @like.destroy
    redirect_to("/home/top")
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_current_user

  def index
    @search = User.search(params[:q])
    @users = @search.result
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(name: params[:name], email: params[:email], password: params[:password], password_confirmation: params[:password_confirmation])

        if params[:image]
          @user.image_name = "#{@user.email}.png"
          image = params[:image]
          File.binwrite("public/user_images/#{@user.image_name}",image.read)

        else
          @user.image_name ='no-image.png'
        end

        if @user.save
          flash[:notice] = "ユーザー登録が完了しました"
          session[:user_id] = @user.id
          redirect_to("/home/top")
        else
          flash[:notice] = "登録できませんでした"
          render("users/new")
        end
  end

  def edit
  end

  def update
    @current_user.name = params[:name]
    @current_user.email = params[:email]
    @current_user.password = params[:password]
    @current_user.password_confirmation = params[:password_confirmation]
    if @current_user.save
      flash[:notice] = "編集が完了しました"
      redirect_to("/home/top")
    else
      flash[:notice] = "編集ができませんでした"
      render("home/top")
    end
  end

  def login_form
  end

  def login
      @user=User.find_by(email: params[:email],
                         password: params[:password])
      if @user
        session[:user_id] = @user.id
        flash[:notice] = "ログインしました"
        redirect_to("/home/top")
      else
        @error_message = "メールアドレスまたはパスワードが間違っています"
        render("home/top")
      end
  end

  def logout
      session[:user_id] = nil
      flash[:notice] = "ログアウトしました"
      redirect_to("/home/top")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/community/top.html.erb
<p>コミュニティ一覧</p>

<p>Find me in app/views/community/top.html.erb</p>

<li class="community-button button-link">
  <%= link_to community_conversation_path do %><%= image_tag 'bin.png'%><% end %>
</li>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Handshakes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="top-main-content">
    <% @search_posts.each do |post| %>
    <li>
      <div class="button-link modal-main-content" id="-datail">
        <p class="main-content-title"><span><%= post.title.truncate(12) %></span></p>
        <p class="main-content-text"><%= post.content.truncate(40) %></p>
      </div>
      <div class="modal-main-content-detail">
        <div class="main-content-set">
          <div class="content-detail">
            <p class="datail-title">『<%= post.title %>』</p>
            <p class="datail-text"><%= post.content %></p>
          </div>
          <div class="content-datail-footer">
            <p class="content-detail-borderline"></p>
            <div class="handshake-image button-link">
              <%= image_tag 'handshake.png' %>
              <% if Like.find_by(user_id: @current_user.id,post_id: post.id)%>
                <%= link_to("いいね！済み", "/likes/#{post.id}/destroy",{method: "post"})%>
              <% else %>
                <%= link_to("いいね！", "/likes/#{post.id}/create",{method: "post"})%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="main-content-footer">
        <p class="main-content-borderline"></p>
        <div class="handshake-image button-link">
          <%= image_tag 'handshake.png' %>
          <% if Like.find_by(user_id: @current_user.id,post_id: post.id)%>
            <%= link_to("いいね！済み", "/likes/#{post.id}/destroy",{method: "post"})%>
          <% else %>
            <%= link_to("いいね！", "/likes/#{post.id}/create",{method: "post"})%>
          <% end %>
        </div>
      </div>
    </li>
    <% end %>
  </div>
  </body>
</html>

app/views/home/list.html.erb
    <div class="top-main-content">
      <% @posts.each do |post| %>
      <li>
        <div class="button-link modal-main-content" id="-datail">
          <p class="main-content-title"><span><%= post.title.truncate(12) %></span></p>
          <p class="main-content-text"><%= post.content.truncate(40) %></p>
        </div>
        <div class="modal-main-content-detail">
          <div class="main-content-set">
            <div class="content-detail">
              <p class="datail-title">『<%= post.title %>』</p>
              <p class="datail-text"><%= post.content %></p>
            </div>
            <div class="content-datail-footer">
              <p class="content-detail-borderline"></p>
              <div class="handshake-image button-link">
                <%= image_tag 'handshake.png' %>
                <% if Like.find_by(user_id: @current_user.id,post_id: post.id)%>
                  <%= link_to("いいね！済み", "/likes/#{post.id}/destroy",{method: "post"})%>
                <% else %>
                  <%= link_to("いいね！", "/likes/#{post.id}/create",{method: "post"})%>
                <% end %>
                <div class="destroy-post button-link">
                  <%= link_to("削除","/home/#{post.id}/destroy",{method: "post"})%>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="main-content-footer">
          <p class="main-content-borderline"></p>
          <div class="handshake-image button-link">
            <%= image_tag 'handshake.png' %>
            <% if Like.find_by(user_id: @current_user.id,post_id: post.id)%>

              <%= link_to("いいね！済み", "/likes/#{post.id}/destroy",{method: "post"})%>
            <% else %>
              <%= link_to("いいね！", "/likes/#{post.id}/create",{method: "post"})%>
            <% end %>
          </div>
        </div>
      </li>
      <% end %>
    </div>

app/views/home/mail.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Handshakes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="ml">メール一覧</div>
<ul class="mail-datail">
  <li>
      <p class="btn-flat-simple">
        <i class="fa fa-caret-right"></i> 参加
      </p>
      <p class="mail-list button-link">[コミュニティへの招待メール]あああああああああああああ</p>
      <div class="mail-of-text">にしきの新しいスケジュール帳はこれで決まりだ。少し大きいけど見やすくて便利だよ</div>
  </li>
    <li>
        <p class="btn-flat-simple">
          <i class="fa fa-caret-right"></i> 参加
        </p>
        <p class="mail-list button-link">[コミュニティへの招待メール]あああああああああああああ</p>
        <div class="mail-of-text">にしきの新しいスケジュール帳はこれで決まりだ。少し大きいけど見やすくて便利だよ</div>
    </li>
    <li>
        <p class="btn-flat-simple">
          <i class="fa fa-caret-right"></i> 参加
        </p>
        <p class="mail-list button-link">[コミュニティへの招待メール]あああああああああああああ</p>
        <div class="mail-of-text">にしきの新しいスケジュール帳はこれで決まりだ。少し大きいけど見やすくて便利だよ</div>
    </li>
    <li>
        <p class="btn-flat-simple">
          <i class="fa fa-caret-right"></i> 参加
        </p>
        <p class="mail-list button-link">[コミュニティへの招待メール]あああああああああああああ</p>
        <div class="mail-of-text">にしきの新しいスケジュール帳はこれで決まりだ。少し大きいけど見やすくて便利だよ</div>
    </li>
    <li>
        <p class="btn-flat-simple">
          <i class="fa fa-caret-right"></i> 参加
        </p>
        <p class="mail-list button-link">[コミュニティへの招待メール]あああああああああああああ</p>
        <div class="mail-of-text">にしきの新しいスケジュール帳はこれで決まりだ。少し大きいけど見やすくて便利だよ</div>
    </li>
    <li>
        <p class="btn-flat-simple">
          <i class="fa fa-caret-right"></i> 参加
        </p>
        <p class="mail-list button-link">[コミュニティへの招待メール]あああああああああああああ</p>
        <div class="mail-of-text">にしきの新しいスケジュール帳はこれで決まりだ。少し大きいけど見やすくて便利だよ</div>
    </li>
    <li>
        <p class="btn-flat-simple">
          <i class="fa fa-caret-right"></i> 参加
        </p>
        <p class="mail-list button-link">[コミュニティへの招待メール]あああああああああああああ</p>
        <div class="mail-of-text">にしきの新しいスケジュール帳はこれで決まりだ。少し大きいけど見やすくて便利だよ</div>
    </li>
    <li>
        <p class="btn-flat-simple">
          <i class="fa fa-caret-right"></i> 参加
        </p>
        <p class="mail-list button-link">[コミュニティへの招待メール]あああああああああああああ</p>
        <div class="mail-of-text">にしきの新しいスケジュール帳はこれで決まりだ。少し大きいけど見やすくて便利だよ</div>
    </li>

  </ul>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <script src="application"></script>

    </body>
</html>

app/views/home/question.erb
<ul class="syncer-acdn-parent">
  <div class="qa">Q＆A</div>
	<li class="question-question"><p><a class="syncer-acdn" data-target="syncer-acdn-03">Q.コミュニティの使い方が分かりません。
</a></p>
		<ul id="syncer-acdn-03" class="syncer-acdn-child">
			<li class="question-anser"><a class="question-anser2 href="#syncer-acdn-01">答え</a></li>
		</ul>
	</li>

	<li class="question-question"><p><a class="syncer-acdn" data-target="syncer-acdn-04">Q.アプリに対しての改善点やフィードバックを返したい場合は、コミュニティかフィードバック送信どちらで返したらいいですか。
</a></p>
		<ul id="syncer-acdn-04" class="syncer-acdn-child">
			<li class="question-anser"><a class="question-anser2 href="#syncer-acdn-02">２答え</a></li>
		</ul>
	</li>

  <li class="question-question"><p><a class="syncer-acdn" data-target="syncer-acdn-05">Q.報告の基準が分かりません。
</a></p>
		<ul id="syncer-acdn-05" class="syncer-acdn-child">
			<li class="question-anser"><a class="question-anser2 href="#syncer-acdn-03">３答え</a></li>
		</ul>
	</li>

  	<li class="question-question"><p><a class="syncer-acdn" data-target="syncer-acdn-06">Q.個人情報は何に使っているのですか？
  </a></p>
  		<ul id="syncer-acdn-06" class="syncer-acdn-child">
  			<li class="question-anser"><a class="question-anser2 href="#syncer-acdn-04">4答え</a></li>
  		</ul>
  	</li>

    <li class="question-question"><p><a class="syncer-acdn" data-target="syncer-acdn-07">Q.コミュニティから抜けるにはどうしたらいいですか？
  </a></p>
  		<ul id="syncer-acdn-07" class="syncer-acdn-child">
  			<li class="question-anser"><a class="question-anser2 href="#syncer-acdn-05">5答え</a></li>
  		</ul>
  	</li>

    <li class="question-question"><p><a class="syncer-acdn" data-target="syncer-acdn-08">Q.報告されるとどうなりますか？
    </a></p>
      <ul id="syncer-acdn-08" class="syncer-acdn-child">
        <li class="question-anser"><a class="question-anser2 href="#syncer-acdn-06">6答え</a></li>
      </ul>
    </li>

    <li class="question-question"><p><a class="syncer-acdn" data-target="syncer-acdn-09">Q.画像が読み込めません
    </a></p>
      <ul id="syncer-acdn-09" class="syncer-acdn-child">
        <li class="question-anser"><a class="question-anser2 href="#syncer-acdn-07">7答え</a></li>
      </ul>
    </li>

</ul>

app/views/home/question.html.erb
<div class="syncer-acdn-parent">
  <div class="qa">Q＆A</div>

  	<div class="question-question">
      <li>
        <a class="syncer-acdn button-link" data-target="syncer-acdn-01">Q.コミュニティの使い方が分かりません。</a>
    		<div id="syncer-acdn-01" class="syncer-acdn-child"><a>A.</a></div>
      </li>
      <li>
        <a class="syncer-acdn button-link" data-target="syncer-acdn-02">Q.アプリに対しての改善点やフィードバックを返したい場合は、コミュニティかフィードバック送信どちらで返したらいいですか。</a>
    		<div id="syncer-acdn-02" class="syncer-acdn-child"><a>A.</a></div>
      </li>
      <li>
        <a class="syncer-acdn button-link" data-target="syncer-acdn-03">Q.報告の基準が分かりません。</a>
    		<div id="syncer-acdn-03" class="syncer-acdn-child"><a>A.</a></div>
      </li>
      <li>
        <a class="syncer-acdn button-link" data-target="syncer-acdn-04">Q.個人情報は何に使っているのですか？</a>
        <div id="syncer-acdn-04" class="syncer-acdn-child"><a>A.</a></div>
      </li>
      <li>
        <a class="syncer-acdn button-link" data-target="syncer-acdn-05">Q.コミュニティから抜けるにはどうしたらいいですか？</a>
        <div id="syncer-acdn-05" class="syncer-acdn-child"><a>A.</a></div>
      </li>
      <li>
        <a class="syncer-acdn button-link" data-target="syncer-acdn-06">Q.報告されるとどうなりますか？</a>
        <div id="syncer-acdn-06" class="syncer-acdn-child"><a>A.</a></div>
      </li>
      <li>
        <a class="syncer-acdn button-link" data-target="syncer-acdn-07">Q.画像が読み込めません</a>
        <div id="syncer-acdn-07" class="syncer-acdn-child"><a>A.</a></div>
      </li>
    </div>
</div>

app/views/home/top.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Handshakes3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>


<div class="top-main-content-group">
</div>
  <div class="top-main-content">
    <p class="content-heading">『週間』</p>
    <% @posts.each do |post| %>
    <li>
      <div class="button-link modal-main-content" id="-datail">
        <p class="main-content-title"><span><%= post.title.truncate(12)%></span></p>
        <p class="main-content-text"><%= post.content.truncate(40) %></p>
      </div>
      <div class="modal-main-content-detail">
        <div class="main-content-set">
          <div class="content-detail">
            <p class="datail-title">『<%= post.title %>』</p>
            <p class="datail-text"><%= post.content %></p>
          </div>
          <div class="content-datail-footer">
            <p class="content-detail-borderline"></p>
            <div class="handshake-image button-link">
              <%= image_tag 'handshake.png' %>
              <% if @current_user %>
              <% if Like.find_by(user_id: @current_user.id,post_id: post.id)%>
                          <%= link_to("いいね！済み", "/likes/#{post.id}/destroy",{method: "post"})%>
                        <% else %>
                          <%= link_to("いいね！", "/likes/#{post.id}/create",{method: "post"})%>
                        <% end %>
              <% else %>
              <%= link_to("いいね！", "/home/not_login")%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="main-content-footer">
        <p class="main-content-borderline"></p>
        <div class="handshake-image button-link">
          <%= image_tag 'handshake.png' %>
          <% if @current_user %>
          <% if Like.find_by(user_id: @current_user.id,post_id: post.id)%>
            <%= link_to("いいね！済み", "/likes/#{post.id}/destroy",{method: "post"})%>
          <% else %>
            <%= link_to("いいね！", "/likes/#{post.id}/create",{method: "post"})%>
          <% end %>
          <% else %>
          <%= link_to("いいね！", "/home/not_login")%>
          <% end %>
        </div>
      </div>
    </li>
    <% end %>
  </div>









    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <script src="application"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Handshakes3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <script src="application"></script>
  </head>

  <body>
    <header>
     <div class="header-logo">
       <%= link_to home_top_path do %> <%= image_tag 'header-logo.png' %> <% end %>
     </div>
     <dl class="searchbox">
      <%= search_form_for @search, url: home_index_path do |f| %>
        <dt><%= f.text_field :title_or_content_cont, placeholder: '検索するテキストを入力...' %></dt>
        <dd><%= f.submit ("検索") , class: 'search-btn'%></dd>
      <% end %>
     </dl>
     <ul class="header-menus">
       <% if @current_user == nil%>
       <li class = "button-link">
         <%= link_to("無料会員登録","/users/new")%>
       </li>
       <% end %>
       <div class =header-manpen2>
       <li id="modal-open" class="button-link">
          <%= image_tag 'manpen2.png' %>
       </li>
       </div>
       <div class =header-account>
       <li id="modal-action" class="button-link">
         <%= image_tag 'account.png' %>
       </li>
       </div>
     </ul>
   </header>

   <% if flash[:notice] %>
       <div id="notice" class="flash">
         <%= flash[:notice] %>
       </div>
   <% end %>


   <div id="modal-content">
     <div class="modal-content-set">
       <%= form_tag("/home/create") do %>
       <p class="push-close"><a id="modal-close" class="button-link">
         <%= image_tag 'batu.png' %>
       </a></p>
       <p id="modal-submit" class="push-submit">
         <input type="image" src="/assets/submit-f629c54f1c9984b668aa7b5f9387540b20cc639669f207e6eaddaa23f24e61a7.png" style="
             width: 30px;
             height: 30px;
         ">
       </p>
       <div class="content-checkbox">
         <p><input type="checkbox" name="check" value="prop" id="content-title">タイトル</p>
         <p><input type="checkbox" name="check" value="prop" id="content-text">画像挿入</p>
       </div>

      <p id="p01" class="submit-title">
        <input name="title">
      </p>
      <p id="p02"><input type="file" name="image"></p>
        <div class="submit-text">
          <textarea name="content" rows="8" cols="80"></textarea>
        </div>
        <%end%>
     </div>

    </div>

   <div id="modal-overlay"></div>

   <div id="modal-actionmenu" class="header-actionmenu">
     <div class="account-img">
       <% if @current_user %>
        <img src="<%= "/user_images/#{@current_user.image_name}"%>">
      <% else %>
        <img src="<%= "/user_images/account.png"%>">
      <% end %>
     </div>
     <p class="user-name">
       <% if @current_user %>
        <%= @current_user.name %>
      <% else %>
        guest
      <% end %>
     </p>
     <ul class="action-menus">
       <% if @current_user %>
        <li class="menus-button button-link">
          <%= link_to("/home/list") do %><%= image_tag 'comment.png'%><% end %>
        </li>
        <li class="menus-button button-link">
          <%= link_to community_top_path do %><%= image_tag 'bin.png'%><% end %>
        </li>
        <li class="menus-button button-link">
          <%= link_to home_mail_path do %> <%= image_tag 'mail.png'%> <% end %>
        </li>
        <li id="modal-setup" class="menus-button button-link">
          <%= image_tag 'setup.png'%>
        </li>
      <% else %>
      <div class="menus-button-opacity">
         <li class="menus-button">
           <%= image_tag 'comment.png'%>
         </li>
         <li class="menus-button">
           <%= image_tag 'bin.png'%>
         </li>
         <li class="menus-button">
           <%= image_tag 'mail.png'%>
         </li>
         <li  class="menus-button">
           <%= image_tag 'setup.png'%>
         </li>
        </div>
      <% end %>
        <li class="menus-button button-link">
            <% if session[:user_id]%>
                <div class="logout-button">
                  <%= form_tag users_logout_path do %><input type="image" src="/assets/logout.png"><% end %>
                </div>
            <%else%>
                <div id = "modal-login">
                  <%= image_tag 'login.png'%>
                </div>
            <%end%>
        </li>
     </ul>
     <div class="action-option">
       <p class="button-link  question-color"><%= link_to 'Q&A', '/home/question',:style=>"color:white;" %></p>
       <p id="modal-feedback" class="button-link">フィードバックの送信</p>
       <p class="button-link">Handshakesについて</p>
     </div>
  </div>

   <div id="modal-feedback-screen">
    <p class="feedback-title">フィードバックの送信</p>
    <button type="button" id="feedbackClose" class="close">&times;</button>
    <textarea placeholder="お客様の思いをできる範囲で汲み取りながら向上して行きたいと考えています。ですので、ご意見や、感想、問題点をご記入いただければ嬉しいです。"></textarea>
    <input type="submit" value="送信">
   </div>

    <%if @error_message %>
       <div class="form-error">
         <%= @error_message %>
        </div>
    <% end %>

    <%= form_tag("/users/login") do %>
     <div id="modal-login-form">
         <div class="login-textarea0">
           <p class=login-daimei>handshakesにログイン</p>
           <div class="login-textarea">
             <li>
               <input placeholder="メールアドレス" name="email">
             </li>
             <li>
               <input placeholder="パスワード" name="password">
             </li>
           </div>
           <div class="login-submit">
               <input type="submit" value="ログイン">
           </div>
        </div>
      </div>
    <% end %>

    <% if @current_user %>
          <%= form_tag("/users/update",{multipart: true}) do %>
          <div id="modal-setup-screen">
            <p class="setup-title-update">アカウントの編集ができます。</p>
            <%= image_tag 'account.png'%>
            <div class="setup-name-update">
                <input placeholder="name" name="name" value="<%= @current_user.name %>">
            </div>
            <div class="setup-textarea-update">
                <li>
                  <p>メールアドレス</p>
                  <input name="email" value="<%= @current_user.email %>">
                </li>
                <li>
                  <p>パスワード</p>
                  <input name="password" value="<%= @current_user.password %>">
                </li>
                <li>
                  <p>パスワード　確認</p>
                  <input name="password_confirmation" value="<%= @current_user.password_confirmation %>">
                </li>
            </div>
            <div class="setup-submit-update">
                <input type="submit" value="保存">
            </div>
          </div>
        <% end %>
      <% end %>

    <%= yield %>


  </body>
</html>

app/views/messages/_message.html.erb
<% cache message do %>
  <div class="message">
    <p><%= message.content %></p>
  </div>
<% end %>

app/views/rooms/show.html.erb
<h1>Chat room</h1>

<div id="messages">
  <%= render @messages %>
</div>
<div class="speak-text">
  <form id="form-id">
    <label>Say something:</label><br>
    <textarea  type="text" data-behavior="room_speaker"></textarea>
  
  </form>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<%= form_tag("/users/create",{multipart:true}) do %>
   <div class="create_account">
     <p class="setup-title">コミュニティ機能と投稿機能をご利用いただく前にアカウントの登録をお願い致します。</p>
     <%= image_tag 'account.png'%>
     <input name="image"type="file">
    <div class="setup-name">
      <input placeholder="name" name="name" value="<%= @user.name %>">
    </div>
     <div class="setup-textarea">
       <li>
         <p>メールアドレス</p>
         <input name="email" value="<%= @user.email %>">
       </li>
       <li>
         <p>パスワード</p>
         <input name="password">
       </li>
       <li>
         <p>パスワード　確認</p>
         <input name="password_confirmation">
       </li>
     </div>
     <div class="setup-submit">
       <input type="submit" value="確認">
     </div>
   </div>
<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>